# Docker compose file to run the API on the server
# using the latest deployed image from Docker Hub

services:
  api:
    image: kinp/pk-central-v2:2.0.5
    ports:
      - "5500:5500"
    env_file:
      - .env
    restart: always
